DROP DATABASE IF EXISTS yeticave;
CREATE DATABASE yeticave
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_general_ci;

USE yeticave;

CREATE TABLE categories (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  date_registration DATETIME DEFAULT NOW(),
  email VARCHAR(128) NOT NULL UNIQUE,
  login VARCHAR(255) NOT NULL UNIQUE,
  password CHAR(64) NOT NULL,
  contact VARCHAR(255)
);

CREATE TABLE lots (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  start_date DATETIME DEFAULT NOW(),
  description VARCHAR(255),
  image VARCHAR(255),
  start_price INT UNSIGNED,
  end_date DATETIME DEFAULT NOW(),
  step INT UNSIGNED,
  user_id BIGINT UNSIGNED,
  winner_id BIGINT UNSIGNED,
  category_id BIGINT UNSIGNED,

  FOREIGN KEY (user_id)
    REFERENCES users (id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  FOREIGN KEY (winner_id)
    REFERENCES users (id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  FOREIGN KEY (category_id)
    REFERENCES categories (id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE TABLE rates (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  date DATETIME DEFAULT NOW(),
  cost INT UNSIGNED,
  user_id BIGINT UNSIGNED,
  lot_id BIGINT UNSIGNED,

  FOREIGN KEY (user_id)
    REFERENCES users (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  FOREIGN KEY (lot_id)
    REFERENCES lots (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
