DROP DATABASE IF EXISTS yeticave;
CREATE DATABASE yeticave
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

USE yeticave;

CREATE TABLE categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  symbolic_code VARCHAR(255)
);

CREATE TABLE lot (
  id INT AUTO_INCREMENT PRIMARY KEY,
  start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  description VARCHAR(255),
  image VARCHAR(255),
  start_price INT,
  end_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  step INT
);

CREATE TABLE rate (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  cost INT
);

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date_registration TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  email VARCHAR(128) UNIQUE,
  login VARCHAR(255) UNIQUE,
  password CHAR(64),
  contact VARCHAR(255)
);
